### ISSUE TITLE
Add features

### ISSUE THREAD

**Issue by odehalaa** [Alplox/teles#2]
First and foremost, I want to express my gratitude for the fantastic code and setup; it's working perfectly. Additionally, I have a couple of suggestions that I hope can be considered:

   1-  Implement a feature to change the channel after the initial channel selection.
   2-  Introduce a new page featuring a live TV list that includes a single channel for live viewing.

Thanks

**Comment by Alplox** [comment]
Suggestion number 1 implemented in version 0.16 (button that says "cambiar" (change))
for the suggestion 2 for now the site it's primary focus is displaying multiples channels so I (for now) would not be focusing on doing a one display main style.
I can leave you with other project more in line with that https://github.com/Alplox/la-tele at the very least

Thanks for the suggestions
