### ISSUE TITLE
Live TV 

### ISSUE THREAD

**Issue by odehalaa** [Alplox/teles#5]
Need to thank you for the new update really amazing updates and please the last thing need to add single view option to see only one channel only.

Regards

**Comment by odehalaa** [comment]
and if possible to icon for channels not only by flag

**Comment by odehalaa** [comment]
![image](https://github.com/Alplox/teles/assets/89680790/6ad82d03-c43b-4e54-a7f1-0d26ff19c637)
 live view like this please

**Comment by Alplox** [comment]
> and if possible to icon for channels not only by flag

For what else are you asking here? can you please elaborate or show examples

**Comment by odehalaa** [comment]
I need to thank you again for your amazing efforts and  please to create a new layout as showed on the picture for single channel same time like (1,2,3,4,12) number of rows and add single channel to watch only one channel same time  and the channel on the right side and the channel list on the left side please same as live tv on any tv receiver.

**Comment by Alplox** [comment]
Sort of done the single view in v0.17 but the channel selection bar is not always visible.

Will keep thread open as a reminder for myself to maybe try adding single view with the bar visible with the option to hide it in v0.18 
![vision-unica](https://github.com/Alplox/teles/assets/42575576/778edf67-7646-4ca9-9c95-c21e84d18fe3)

**Comment by odehalaa** [comment]
Thanks Alpox for you amazing updates , really amazing solution, I tired to use v17.0 from GitHub but I think there is error can't se any channel,
for V18 really it will be amazing feature
Thanks again for your efforts
