### ISSUE TITLE
Cambiar channesl list 

### ISSUE THREAD

**Issue by odehalaa** [Alplox/teles#6]
Hi,

I need to ask you when press on Cambiar will get the channel list but we can't see the countries , I recommend please to use the same design of CANALS

![image](https://github.com/Alplox/teles/assets/89680790/b7827443-18c1-4c6a-bd14-0a4cb0706bc1)

like this 

![image](https://github.com/Alplox/teles/assets/89680790/4a1f7cbb-b85a-42f7-9025-20192c3c9366)

and the last idea if possible to add icon of channels options if we don't use flag 

Regards

**Comment by Alplox** [comment]
Done in v0.17
For the logos inside the buttons edit "crearBotonesParaCanales" (main.js)  in case your channels use/have logos
